config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'

  get 'inicio/home'

  get 'inicio/start'

  post 'inicio/edit'

  get 'aresponse/:id' => 'inicio#start'

  get 'cerar' => 'options#cerar'

  root "inicio#index"
  resources :instancia
  resources :options

end

app/models/instancium.rb
class Instancium < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	@id_ins=0

  def index
  	@ola=1

  	@opcion = Option.where()

  end


  def home
  end


  def edit

  	id_op = params[:opt]
  	votado = Option.where(id: id_op).take
  	votado.votos+=1;
  	votado.save

  	respond_to do |format|
        format.html { redirect_to root_path, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
    end
   end


  def start
  	coso = params[:id]
    total = Option.count

    i=0
    arreglo = Array.new

    Option.where(instancia: coso).each do |opt|
    	id = opt.id
      name= opt.name
      votos= opt.votos
      descripcion = opt.descripcion
      disponible= opt.disponible
      result = {:id => id, :name => name, :votos => votos, :descripcion => descripcion, :disponible => disponible}
      arreglo.push(result)
    end
    response = {:opciones => arreglo}
    render:json => response
  end


end

app/controllers/instancia_controller.rb
class InstanciaController < ApplicationController
  before_action :set_instancium, only: [:show, :edit, :update, :destroy]

  # GET /instancia
  # GET /instancia.json
  def index
    @instancia = Instancium.all
  end

  # GET /instancia/1
  # GET /instancia/1.json
  def show
  end

  # GET /instancia/new
  def new
    @instancium = Instancium.new
  end

  # GET /instancia/1/edit
  def edit
  end

  # POST /instancia
  # POST /instancia.json
  def create
    @instancium = Instancium.new(instancium_params)

    respond_to do |format|
      if @instancium.save
        format.html { redirect_to @instancium, notice: 'Instancium was successfully created.' }
        format.json { render :show, status: :created, location: @instancium }
      else
        format.html { render :new }
        format.json { render json: @instancium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instancia/1
  # PATCH/PUT /instancia/1.json
  def update
    respond_to do |format|
      if @instancium.update(instancium_params)
        format.html { redirect_to @instancium, notice: 'Instancium was successfully updated.' }
        format.json { render :show, status: :ok, location: @instancium }
      else
        format.html { render :edit }
        format.json { render json: @instancium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instancia/1
  # DELETE /instancia/1.json
  def destroy
    @instancium.destroy
    respond_to do |format|
      format.html { redirect_to instancia_url, notice: 'Instancium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instancium
      @instancium = Instancium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instancium_params
      params.require(:instancium).permit(:name, :votos, :disponible, :descripcion, :winner, :otherx)
    end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  def cerar
    Option.all.each do |op|
      op.votos=0
      op.save
    end

    response = {:promociones => "hola"}
    render:json => response
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)
    @option.votos=0

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:name, :votos, :disponible, :instancia, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper

	@insta_actual=nil

	 def cargo
	 	puts Instancium.count
	 	
	 	if Instancium.count >0 
	  		ins = Instancium.where(disponible: 1).take
	  
	  			if(ins !=nil)
	  				@insta_actual=ins
	  				@id_ins=ins.id
	  				return ins.name
	  				
	  				
	  			end

	  		return "NO hay Instancias disponibles"
	  	end
	  	return "no hay instancias"

 	 end

 	 def ruta
 	 	if(@insta_actual !=nil)
 	 		return instancium_path(@insta_actual)
 		 end
 	end


 	 def describir
 	 	if(@insta_actual !=nil)
 	 		return @insta_actual.descripcion
 		 end
 	 end






end

app/helpers/instancia_helper.rb
module InstanciaHelper
end

app/helpers/options_helper.rb
module OptionsHelper

	def instar
		total = Instancium.count


    i=0
    arreglo = Array.new
    subd = Array.new
    subd.push("Sin instancia")
    subd.push("Sin instancia")
    arreglo.push(subd)

    Instancium.where(disponible: 1).each do |ins|
    	subx = Array.new
    	subx.push(ins.name)
    	subx.push(ins.name)
    	arreglo.push(subx)
	end

	return arreglo
	end

    


end

app/views/inicio/home.html.erb
<h1>hola/h1>

app/views/inicio/index.html.erb
<div class="page-header">
<h5 id="info" class="hidden">vista</h5>
  <h1>Bienvenido  <br><small>Aquí encontrara las opciones para el cargo</small></h1>
</div>


<div class="jumbotron">
  <h2 id="cargo"><%=cargo() %></h2>
  <section>
<p><%= describir() %> </p>
</section>
  <p><a class="btn btn-primary btn-primary center-block" href=<%=ruta()%> role="button">Saber Más</a></p>
</div>


<!-- Modal -->

<div class="moi">
		
	</div>


<%= form_tag("inicio/edit", method: "post") do %>
	<div class="conte">
		
	</div>
	
	<div class="subm">
		
	
  <%= submit_tag "VOTAR",  class: "btn btn-default btn-lg" %>
  </div>



<% end %>

app/views/inicio/start.html.erb
<h1>Inicio#start</h1>
<p>Find me in app/views/inicio/start.html.erb</p>

app/views/instancia/_form.html.erb
<%= form_for(@instancium) do |f| %>
  <% if @instancium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instancium.errors.count, "error") %> prohibited this instancium from being saved:</h2>

      <ul>
      <% @instancium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :votos %><br>
    <%= f.number_field :votos %>
  </div>
  <div class="field">
    <%= f.label :disponible %><br>


    <%= f.select :disponible, options_for_select( [ ["Disponible ",1],["No disponible", 0]] )%>


   
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :otherx %><br>
    <%= f.text_field :otherx %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instancia/edit.html.erb
<h1>Editing Instancium</h1>

<%= render 'form' %>

<%= link_to 'Show', @instancium %> |
<%= link_to 'Back', instancia_path %>

app/views/instancia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instancia</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Votos</th>
      <th>Disponible</th>
      <th>Descripcion</th>
      <th>Winner</th>
      <th>Otherx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instancia.each do |instancium| %>
      <tr>
        <td><%= instancium.name %></td>
        <td><%= instancium.votos %></td>
        <td><%= instancium.disponible %></td>
        <td><%= instancium.descripcion %></td>
        <td><%= instancium.winner %></td>
        <td><%= instancium.otherx %></td>
        <td><%= link_to 'Show', instancium %></td>
        <td><%= link_to 'Edit', edit_instancium_path(instancium) %></td>
        <td><%= link_to 'Destroy', instancium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instancium', new_instancium_path %>
<br>
<br>
<%= link_to 'Ver opciones', options_path %>

app/views/instancia/new.html.erb
<h1>New Instancium</h1>

<%= render 'form' %>

<%= link_to 'Back', instancia_path %>

app/views/instancia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instancium.name %>
</p>

<p>
  <strong>Votos:</strong>
  <%= @instancium.votos %>
</p>

<p>
  <strong>Disponible:</strong>
  <%= @instancium.disponible %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @instancium.descripcion %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @instancium.winner %>
</p>

<p>
  <strong>Otherx:</strong>
  <%= @instancium.otherx %>
</p>

<%= link_to 'Edit', edit_instancium_path(@instancium) %> |
<%= link_to 'Back', instancia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Votar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Votacion</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :votos %><br>
    <%= f.number_field :votos %>
  </div>
  <div class="field">
    <%= f.label :disponible %><br>
    <%= f.number_field :disponible %>
  </div>
  <div class="field">
    <%= f.label :instancia %><br>
    <%= f.select :instancia, options_for_select( instar() )%>

  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>
<h5 id="info" class="hidden">options</h5>

<h1 >Listing Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Votos</th>
      <th>Disponible</th>
      <th>Instancia</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.name %></td>
        <td><%= option.votos %></td>
        <td><%= option.disponible %></td>
        <td><%= option.instancia %></td>
        <td><%= option.descripcion %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>
<br>
<br>
<%= link_to 'Ver opciones', instancia_path %>
<button class="btn btn-default" id="cerar"type="submit">Hacer cero</button>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option.name %>
</p>

<p>
  <strong>Votos:</strong>
  <%= @option.votos %>
</p>

<p>
  <strong>Disponible:</strong>
  <%= @option.disponible %>
</p>

<p>
  <strong>Instancia:</strong>
  <%= @option.instancia %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @option.descripcion %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>